### ISSUE TITLE
Add support for list indices within `assocPath`

### ISSUE THREAD

**Issue by luisvasq** [connor-makowski/pamda#11]
It'd be great if `assocPath` could support list indices, similar to the behavior in [Ramda’s `assocPath`](https://ramdajs.com/repl/?v=0.30.1#?const%20obj%20%3D%20%7B%20a%3A%20%5B%7B%20b%3A%201%20%7D%2C%20%7B%20c%3A%202%20%7D%5D%20%7D%0AR.assocPath%28%5B%27a%27%2C%201%2C%20%27c%27%5D%2C%203%29%28obj%29). This would be very helpful when working with nested dictionaries that contain lists.

**Comment by connor-makowski** [comment]
Closing with b4dbdb468296fa879b8833326cf52a3f7a6e3ba1
